RIPPLE_LOW_HZ:
  80

RIPPLE_HIGH_HZ:
  140

RIPPLE_BANDS:
  [[ 80, 140]]

RIPPLE_THRESHOLD_SD:
  2.0

RIPPLE_MIN_DURATION_MS:
  10

FS_iEEG:
  2000

FS_EEG:
  200

iEEG_ROIS:
  ["AHL", "AHR", "PHL", "PHR", "ECL", "ECR", "AL", "AR"]
