DIR_SUBJECT:
  f"./data/Sub_{sub}/"

DIR_SESSION:
  f"./data/Sub_{sub}/Session_{session}/"

PATH_TRIALS_INFO:
  f"./data/Sub_{sub}/Session_{session}/trials_info.csv"

PATH_SPIKE_TIMES:
  f"./data/Sub_{sub}/Session_{session}/spike_times/{roi}.pkl"

PATH_iEEG:
  f"./data/Sub_{sub}/Session_{session}/iEEG/{roi}.pkl"

PATH_iEEG_RIPPLE_BAND:
  f"./data/Sub_{sub}/Session_{session}/iEEG_ripple_preprocessed/{roi}.pkl"

PATH_RIPPLE:
  f"./data/Sub_{sub}/Session_{session}/ripple/{roi}.pkl"
  # f"./data/rips_df/{roi}.pkl"

PATH_NT:
  f"./data/Sub_{sub}/Session_{session}/NT/{roi}.npy"

PATH_NT_z:
  f"./data/Sub_{sub}/Session_{session}/NT/{roi}_z_by_session.npy"
