DIR:
  SUBJECT:
    f"./data/Sub_{sub}/"

  SESSION:
    f"./data/Sub_{sub}/Session_{session}/"

PATH:
  TRIALS_INFO:
    f"./data/Sub_{sub}/Session_{session}/trials_info.csv"

  SPIKE_TIMES:
    f"./data/Sub_{sub}/Session_{session}/spike_times/{roi}.pkl"

  iEEG:
    f"./data/Sub_{sub}/Session_{session}/iEEG/{roi}.pkl"

  iEEG_RIPPLE_BAND:
    f"./data/Sub_{sub}/Session_{session}/iEEG_ripple_preprocessed/{roi}.pkl"

  RIPPLE:
    f"./data/Sub_{sub}/Session_{session}/SWR_p/{roi}.pkl"

  RIPPLE_MINUS:
    f"./data/Sub_{sub}/Session_{session}/SWR_m/{roi}.pkl"

  NT:
    f"./data/Sub_{sub}/Session_{session}/NT/{roi}_match_all.npy"

  NT_Z:
    f"./data/Sub_{sub}/Session_{session}/NT/{roi}_match_all_z_by_session.npy"

# PATH_TRIALS_INFO:
#   f"./data/Sub_{sub}/Session_{session}/trials_info.csv"

# PATH_SPIKE_TIMES:
#   f"./data/Sub_{sub}/Session_{session}/spike_times/{roi}.pkl"

# PATH_iEEG:
#   f"./data/Sub_{sub}/Session_{session}/iEEG/{roi}.pkl"

# PATH_iEEG_RIPPLE_BAND:
#   f"./data/Sub_{sub}/Session_{session}/iEEG_ripple_preprocessed/{roi}.pkl"

# PATH_RIPPLE:
#   f"./data/Sub_{sub}/Session_{session}/SWR_p/{roi}.pkl"

# PATH_RIPPLE_MINUS:
#   f"./data/Sub_{sub}/Session_{session}/SWR_m/{roi}.pkl"

# PATH_NT:
#   f"./data/Sub_{sub}/Session_{session}/NT/{roi}.npy"

# PATH_NT_Z:
#   f"./data/Sub_{sub}/Session_{session}/NT/{roi}_match_all_z_by_session.npy"



# DIR_SUBJECT:
#   f"./data/Sub_{sub}/"

# DIR_SESSION:
#   f"./data/Sub_{sub}/Session_{session}/"
