RIPPLE:
  TYPES:
    ["SWR+", "SWR-"]
  LOW_HZ:
    80

  HIGH_HZ:
    140

  BANDS:
    [[ 80, 140]]

  THRES_SD:
    3.0

  MIN_DUR_MS:
    10

  BINS:
    pre:
      [-16, -5]
    mid:
      [-5, 6]
    post:
      [6, 17]



# RIPPLE_LOW_HZ:
#   80

# RIPPLE_HIGH_HZ:
#   140

# RIPPLE_BANDS:
#   [[ 80, 140]]

# RIPPLE_THRESHOLD_SD:
#   3.0

# RIPPLE_MIN_DURATION_MS:
#   10


# SWR_BINS:
#   "pre":
#     [-16, -5]
#   "mid":
#     [-5, 6]
#   "post":
#     [6, 17]
