!!omap
    - SUBJECTS:
        - '01'
        - '02'
        - '03'
        - '04'
        - '05'
        - '06'
        - '07'
        - '08'
        - '09'
    - SESSIONS:
        '01':
            - '01'
            - '02'
            - '03'
            - '04'
        '02':
            - '01'
            - '02'
            - '03'
            - '04'
            - '05'
            - '06'
            - '07'
        '03':
            - '01'
            - '02'
            - '03'
        '04':
            - '01'
            - '02'
        '05':
            - '01'
            - '02'
            - '03'
        '06':
            - '01'
            - '02'
            - '03'
            - '04'
            - '05'
            - '06'
            - '07'
        '07':
            - '01'
            - '02'
            - '03'
            - '04'
        '08':
            - '01'
            - '02'
            - '03'
            - '04'
            - '05'
        '09':
            - '01'
            - '02'
    - ROIS:
        '01':
            - AHL
            - AHR
            - AL
            - AR
            - ECL
            - ECR
            - PHL
            - PHR
        '02':
            - AHL
            - AHR
            - AL
            - AR
            - ECL
            - ECR
            - PHL
            - PHR
        '03':
            - AHL
            - AHR
            - AL
            - AR
            - ECL
            - ECR
            - PHL
            - PHR
        '04':
            - AHL
            - AHR
            - AL
            - AR
            - ECL
            - ECR
            - PHL
            - PHR
        '05':
            - AHL
            - AHR
            - AL
            - AR
            - ECL
            - ECR
            - PHL
            - PHR
        '06':
            - AHL
            - AHR
            - AL
            - AR
            - ECL
            - ECR
            - PHL
            - PHR
        '07':
            - AHL
            - AHR
            - AL
            - AR
            - ECL
            - ECR
            - PHL
            - PHR
        '08':
            - AHL
            - AHR
            - AL
            - AR
            - ECL
            - ECR
            - PHL
            - PHR
        '09':
            - AHL
            - AHR
            - AL
            - AR
            - ECL
            - ECR
            - PHL
            - PHR
